DROP TABLE `achievements`;--> statement-breakpoint
DROP TABLE `active_methodologies`;--> statement-breakpoint
DROP TABLE `announcementReads`;--> statement-breakpoint
DROP TABLE `announcements`;--> statement-breakpoint
DROP TABLE `assignment_submissions`;--> statement-breakpoint
DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `badges`;--> statement-breakpoint
DROP TABLE `belt_history`;--> statement-breakpoint
DROP TABLE `belts`;--> statement-breakpoint
DROP TABLE `calendar_events`;--> statement-breakpoint
DROP TABLE `challenge_rankings`;--> statement-breakpoint
DROP TABLE `challenge_submissions`;--> statement-breakpoint
DROP TABLE `class_statuses`;--> statement-breakpoint
DROP TABLE `classes`;--> statement-breakpoint
DROP TABLE `coin_transactions`;--> statement-breakpoint
DROP TABLE `collaborative_tools`;--> statement-breakpoint
DROP TABLE `computational_thinking_scores`;--> statement-breakpoint
DROP TABLE `ct_badges`;--> statement-breakpoint
DROP TABLE `ct_exercises`;--> statement-breakpoint
DROP TABLE `ct_submissions`;--> statement-breakpoint
DROP TABLE `gamification_notifications`;--> statement-breakpoint
DROP TABLE `hidden_achievements`;--> statement-breakpoint
DROP TABLE `interactive_projects`;--> statement-breakpoint
DROP TABLE `invite_codes`;--> statement-breakpoint
DROP TABLE `learning_modules`;--> statement-breakpoint
DROP TABLE `learning_topics`;--> statement-breakpoint
DROP TABLE `level_up_history`;--> statement-breakpoint
DROP TABLE `module_badges`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `password_reset_tokens`;--> statement-breakpoint
DROP TABLE `points_history`;--> statement-breakpoint
DROP TABLE `project_activities`;--> statement-breakpoint
DROP TABLE `project_students`;--> statement-breakpoint
DROP TABLE `review_sessions`;--> statement-breakpoint
DROP TABLE `scheduled_classes`;--> statement-breakpoint
DROP TABLE `shifts`;--> statement-breakpoint
DROP TABLE `shop_items`;--> statement-breakpoint
DROP TABLE `specialization_achievements`;--> statement-breakpoint
DROP TABLE `specialization_skills`;--> statement-breakpoint
DROP TABLE `student_achievements`;--> statement-breakpoint
DROP TABLE `student_actions`;--> statement-breakpoint
DROP TABLE `student_attendance`;--> statement-breakpoint
DROP TABLE `student_badges`;--> statement-breakpoint
DROP TABLE `student_ct_badges`;--> statement-breakpoint
DROP TABLE `student_class_enrollments`;--> statement-breakpoint
DROP TABLE `student_enrollments`;--> statement-breakpoint
DROP TABLE `student_equipped_items`;--> statement-breakpoint
DROP TABLE `student_exercise_answers`;--> statement-breakpoint
DROP TABLE `student_exercise_attempts`;--> statement-breakpoint
DROP TABLE `student_exercises`;--> statement-breakpoint
DROP TABLE `student_hidden_achievements`;--> statement-breakpoint
DROP TABLE `student_learning_journal`;--> statement-breakpoint
DROP TABLE `student_points`;--> statement-breakpoint
DROP TABLE `student_progress`;--> statement-breakpoint
DROP TABLE `student_purchased_items`;--> statement-breakpoint
DROP TABLE `student_skills`;--> statement-breakpoint
DROP TABLE `student_specialization_achievements`;--> statement-breakpoint
DROP TABLE `student_specializations`;--> statement-breakpoint
DROP TABLE `student_subject_badges`;--> statement-breakpoint
DROP TABLE `student_subject_points`;--> statement-breakpoint
DROP TABLE `student_topic_doubts`;--> statement-breakpoint
DROP TABLE `student_topic_progress`;--> statement-breakpoint
DROP TABLE `student_wallets`;--> statement-breakpoint
DROP TABLE `students`;--> statement-breakpoint
DROP TABLE `subject_badges`;--> statement-breakpoint
DROP TABLE `subjectEnrollments`;--> statement-breakpoint
DROP TABLE `subject_points_history`;--> statement-breakpoint
DROP TABLE `tasks`;--> statement-breakpoint
DROP TABLE `teacher_activities_history`;--> statement-breakpoint
DROP TABLE `teacher_belt_history`;--> statement-breakpoint
DROP TABLE `teacher_points`;--> statement-breakpoint
DROP TABLE `time_slots`;--> statement-breakpoint
DROP TABLE `topic_assignments`;--> statement-breakpoint
DROP TABLE `topic_class_links`;--> statement-breakpoint
DROP TABLE `topic_comments`;--> statement-breakpoint
DROP TABLE `topic_materials`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `weekly_challenges`;